### ISSUE TITLE
Free jpeg2000 libraries?

### ISSUE THREAD

**Issue by boskar** [ruven/iipsrv#14] opened 2014-04-22 11:48 UTC
Kakadu - yeah, it's probably nice, but it's non-free. We've got some free jpeg2000 libraries.

Some of them are GPU based - as iipsrv is oriented for performance ( comparing to python or java-based image servers ) It'd be very nice to support them as an option. 

We've got: 
CUDA: http://apps.man.poznan.pl/trac/jpeg2k/wiki
CUDA: http://cuj2k.sourceforge.net/‎
CPU: http://www.openjpeg.org/

**Comment by geektortoise** [comment] 2015-01-16 10:52
Hello ruven, 
Firstly, thanks for all your work on iipsrv. It's very useful for us. :-) :+1: 

You said here ( http://iipimage.sourceforge.net/2011/04/iipimage-0-9-9-server-release/ ) than "a fully open source implementation based on openJPEG will be included in the next server release".

Is it still your goal ?
Thanks.

**Comment by ruven** [comment] 2015-01-16 11:36
> Firstly, thanks for all your work on iipsrv. It's very useful for us. :-) :+1:

Thanks!

> a fully open source implementation based on openJPEG will be included in the next server release

I'm afraid it won't make it into this coming version 1.0, but will definitely be in version 1.1.

**Comment by geektortoise** [comment] 2015-01-16 12:05
Ok.

Thanks for your reply. :-)

**Comment by aeschylus** [comment] 2015-07-18 04:40
If someone can point me to the right part of the codebase to integrate these libraries, I would be happy to begin working on a branch to support this goal for the 1.1 release. I also know a number of others who would be interested in this as a technical challenge, both simply integrating the components, and in improving the components themselves (adding gpu support to openJpeg for instance) to bring them up to a superior level when compared with Kakadu.

**Comment by aeschylus** [comment] 2015-07-18 04:40
It seems that @boskar might have some specific ideas as to where to start.

**Comment by ahankinson** [comment] 2015-07-19 10:14
There are efforts underway by the Wellcome Library to get openJPEG up to par with Kakadu.

See:

https://groups.google.com/forum/#!searchin/iiif-discuss/openjpeg/iiif-discuss/apvlLaToKAE/iz9QYO-GGUcJ

https://groups.google.com/forum/#!searchin/iiif-discuss/openjpeg/iiif-discuss/L1k_24sX2mA/e4IVYzvRJlEJ

**Comment by boskar** [comment] 2015-07-20 17:58
Well, We should obviously start here: https://github.com/moravianlibrary/iipsrv-openjpeg and see how good it is at the moment. I suppose there is no other way that reading the code referencing to kakadu and finding equivalents in chosen library... 

http://apps.man.poznan.pl/trac/jpeg2k/wiki does not seem to have library as is, although the encoder/decoder works (tested today). Maybe we should cooperate with the authors about integration?

cuj2k - site does not work due to SF being down. 

On the other hand: there seems to be another alternative (paid): 
http://www.fastcompression.com/products/jpeg2000/cuda-jpeg2000.htm - 
They support jpeg as well, so if *full* integration is ever made - that'd fast as hell.

**Comment by ruven** [comment] 2015-07-21 14:59
I haven't tested it myself, but the openjpeg branch you cite is reportedly around 1000x slower than Kakadu. 

However, as pointed out by @ahankinson there's work under way to optimize openjpeg, so it may become competitive speed-wise in the not too distant future. So, if you're looking for a technical challenge, helping to add SIMD or GPU support to openjpeg could be both very interesting and very useful!

**Comment by stweil** [comment] 2015-10-17 21:33
https://github.com/stweil/iipsrv/tree/openjpeg-api-fixed is based on https://github.com/moravianlibrary/iipsrv-openjpeg, but fixed for latest OpenJPEG. I could process a JP2 file with it, but also observed program crashes. https://github.com/stweil/iipsrv/tree/openjpeg is a branch which merged latest iipsrv. It still needs some API fixes.

**Comment by stweil** [comment] 2015-10-31 10:09
https://github.com/stweil/iipsrv/tree/openjpeg now works with OpenJPEG. It takes a lot of time: PalaisDuLouvre.jp2 (made from PalaisDuLouvre.tif) needs 27 s on my Intel Core i7 notebook.

iipsrv calculates 63 tiles, each of them taking about 0.4 s. If it would use all CPU cores of my notebook (as Kakadu does), the total time could be reduced from 27 s to 7 s.

For PalaisDuLouvre.tif, iipsrv calculates 223 tiles in 0.125 s. I don't have timings with Kakadu.

**Comment by boskar** [comment] 2015-10-31 13:35
Have You tried using multiple instances of iipsrv? It could be a way to parallelize the work...

**Comment by stweil** [comment] 2015-10-31 14:31
@boskar: IMHO that would parallelize the work if there are several parallel requests, but not for each individual request...

**Comment by boskar** [comment] 2015-10-31 15:37
@stweil Sure, You're right. But who needs a single tile? I suppose the client does not download them in row.

**Comment by stweil** [comment] 2016-03-17 14:40
@ruven, are you interested in pull requests to get the OpenJPEG support added? The new code is clearly separated from the Kakadu code and could be disabled by default, so the risk would be low.

**Comment by ruven** [comment] 2016-03-17 15:45
I'm preparing things for the 1.0 release, so let's wait until that's out of the way, then I'll be happy to accept a pull request.

**Comment by ahankinson** [comment] 2016-03-17 15:57
Would it be useful to open a pull request with the understanding that it won't be merged until after 1.0?

**Comment by ruven** [comment] 2016-03-17 16:05
You could do, but any pull will probably be easier if it's based on the final 1.0 code

**Comment by ahankinson** [comment] 2016-03-17 16:08
It's possible to keep a PR up to date with frequent merges from master, so that the accepted PR applies cleanly to the latest revisions. That depends, of course, on the maintainer of the PR staying on top of it. :)

**Comment by stweil** [comment] 2016-03-17 20:03
I just provided PR #61 for anybody interested in trying OpenJPEG support. This PR will be rebased and updated as needed.

**Comment by stweil** [comment] 2016-05-21 14:18
The bad performance of iipsrv with OpenJPEG is mainly caused by the missing support for regionDecoding in the current code: while Kakadu requests the region directly from the JP2 image, OpenJPEG uses the TileManager to calculate a lot of tiles (several hundreds or more for large images), so the time factor of 100 or  1000 is not surprising – the factor will increase with the image size.

**Comment by fastvideo** [comment] 2016-06-12 16:06
Here you can find interesting benchmarks for OpenJPEG and other encoders on CPU and GPU:
[www.fastcompression.com/products/jpeg2000/benchmarks-j2k.htm](url)

**Comment by beaudet** [comment] 2017-03-16 21:44
Not sure what the current state of openjpeg support is with IIP master, but I am retrofitting IIP to embed ICC profiles from the source files into the JPEGs that IIP generates.  However, it seems that only one region from the source image is currently being extracted.  See the screenshot below.  This was found using one of the Wellcome Library's JP2 images and IIP on RedHat EL6 with openjpeg2-2.1.0-7.el6.x86_64 and openjpeg2-devel-2.1.0-7.el6.x86_64 from the EPEL repository and with IIP compiled using configure --enable-openjpeg.

![image](https://cloud.githubusercontent.com/assets/77699/24019874/3b57ed94-0a70-11e7-8c3d-b2838392396b.png)

**Comment by stweil** [comment] 2017-03-16 21:51
I think that the status is still experimental. Nevertheless the effect which you observe looks strange. Perhaps you can try to debug it, for example have a look into the server log output.

**Comment by beaudet** [comment] 2017-03-16 21:57
Yeah, maybe in my free time :)  For now, I'm going to ensure the ICC gets embedded in the resulting image and move on.

**Comment by stweil** [comment] 2017-09-14 15:34
Is this issue still open, or can it be closed?

**Closed** 2019-06-25 11:57 UTC
